language: java
# whitelist
branches:
  only:
    - master
# jdk
jdk:
  - oraclejdk8

before_script:
  - mkdir lib/
  - wget -P lib/ https://github.com/lip6/pnmlframework/blob/gh-pages/plugins/fr.lip6.pnml.framework.3rdpartimports_2.2.12.jar

# script to launch
script: "./build.sh"

cache:
  directories:
    - '$HOME/.m2/repository'
